# Generated by Django 3.1.6 on 2021-02-02 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='previsão_entrega',
            field=models.PositiveSmallIntegerField(verbose_name='Previsão da entrega em dias'),
        ),
    ]
