# Generated by Django 3.1.6 on 2021-02-03 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_produto_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='comprador',
            new_name='cadastrado_por',
        ),
    ]
