# Generated by Django 3.1.6 on 2021-02-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_auto_20210203_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco_oferta',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=99, null=True, verbose_name='Preço do produto em oferta'),
        ),
    ]
