# Generated by Django 3.1.6 on 2021-02-03 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_auto_20210203_1213'),
        ('venda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='descricao',
        ),
        migrations.AddField(
            model_name='item',
            name='imagem',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='produto.produto', verbose_name='Produto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='venda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='venda.venda', verbose_name='Venda'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
