# Generated by Django 3.1.6 on 2021-02-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0002_auto_20210203_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='imagem',
            field=models.CharField(max_length=200),
        ),
    ]
